blog/urls.py
from django.urls import path

from .views import render_posts, render_post

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', render_post, name='post'),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from blog import urls

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Create your views here.
def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})

def render_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id) 
    return render(request, 'post.html', {'post': post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    
    return render(request, 'home.html', {'projects': projects})

blog/templates/post.html
{% extends 'layout.html' %}
  
{% block content %}

    <h2>{{ post.title }}</h2>
    <h3 class="my-2 h5 text-muted">{{ post.date | date:'F jS Y' }}</h3>
    <div class="my-4">
        <p>{{ post.description }}</p>
    </div>
    <img src="{{post.image.url}}" alt="" class="img-fluid"/>
    
{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
  
{% block content %}

<h1 class="text-center card card-body bg-black mb-4 mt-4 shadow-lg">Posts</h1>

    {% for post in posts %}
    
    <div class="p-3">
        <div class="card card-body bg-black">
            <div class="row">
                <div class="col-3">
                    <h2>{{ post.title }}</h2>
                    <p>{{ post.description | truncatechars:100 }}<a href="{% url 'blog:post' post.id %}">read more</a></p>
                    <p>{{ post.date | date:'M d Y'}}</p>  
                </div>
                <div class="col-9">
                    <img src="{{post.image.url}}" alt="{{ post.title }}" class="img-fluid"/>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}
    
{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="row bg-black rounded p-4 mt-4 mb-2 shadow-lg">
    <div class="col-md-4 text-center">
        <img src="{% static 'portfolio/profile.jpg' %}" class="img-fluid img-thumbnail rounded" alt="Responsive image">
    </div>
    <div class="col-md-8 my-auto">
        <h1 class="mb-3">I am <strong>Ignacio Barroso</strong></h1>
        <h3 class="text-muted">Python Backend developer and Cloud & DevOps enthusiast</h3>
        <p>I have professional training to implement solutions in the tech industry with web frameworks such as Flask, FastAPI and Django, with use of both SQL and NoSQL databases, data analysis with Pandas, Numpy and Matplotlib in collaborative environments like Deepnote and GoogleColab. Ability to productive deploy with Docker and clustering with Swarm on Ubuntu Server, in addition to extensive knowledge in Microsoft Azure and other Cloud Service providers of the most demanded for productive, scalable and high availability solutions. I also have good clean code practices, in order to be functional in work environments, and key skills in leadership and initiative.</p>
        <a href="{% static 'portfolio/cv.pdf' %}" class="btn btn-primary rounded my-3" target="_blank">Download CV</a>
    </div>
</header>

<div class="row my-4 text-center">
    
    <h3 class="card card-body bg-black mb-5 mt-4 shadow-lg">My Projects</h3>

    {% for project in projects %}
        
        <div class="col-md-4 p-3">
            <div class="card bg-black card-project shadow">
                <img src="{{project.image.url}}" alt="{{ project.title }}" class="card-img-top">
                <div class="card-body">
                    <h2>{{ project.title }}</h2>
                    <p>{{ project.description }}</p>
                    {% if project.url %}
                    <a href="{{project.url}}" class="btn btn-light rounded btn-sm" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                        </svg>
                        Go to code
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>

    {% endfor %}

</div>

{% endblock %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body class="text-light">
    
    {% include 'partials/navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>

    {% include 'partials/footer.html' %}

</body>
</html>

portfolio/templates/partials/footer.html
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top border-dark">
      <div class="col-md-4 d-flex align-items-center">
        <span class="text-muted">© 2021 Ignacio Barroso</span>
      </div>
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="text-muted" href="https://twitter.com/IgnacioBarroso_" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16"><path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path></svg></a></li>
        <li class="ms-3"><a class="text-muted" href="https://www.linkedin.com/in/juan-ignacio-barroso/" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
            <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"></path>
          </svg></a></li>
        <li class="ms-3"><a class="text-muted" href="https://github.com/IgnacioBarroso" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
          </svg></a></li>
        <li class="ms-3"><a class="text-muted" href="https://instagram.com/_juanibarroso" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
          </svg></a></li>
      </ul>
    </footer>
  </div>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold" href="/">Ignacio Barroso</a>
      <div class="" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="/blog">Personal blog</a>
          </li>
        </ul>
      </div>
    </div>
</nav>